/**
 * AI utility functions using LiteLLM
 * 
 * LiteLLM provides OpenAI-compatible API for multiple LLM providers.
 * Currently configured with Gemini 2.5 Flash for vision capabilities.
 */

const LITELLM_BASE_URL = process.env.LITELLM_BASE_URL;
const LITELLM_API_KEY = process.env.LITELLM_API_KEY;
const LITELLM_MODEL = process.env.LITELLM_MODEL || "gemini/gemini-2.5-flash";

// Gemini 2.5 Flash uses "reasoning tokens" before generating output
// We need to allow enough tokens for both thinking (~1000) and response (~200)
const DEFAULT_MAX_TOKENS = 2000;

export interface AIDescriptionResult {
  description: string;
}

export class AIError extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly statusCode?: number
  ) {
    super(message);
    this.name = "AIError";
  }
}

/**
 * Validates that LiteLLM environment variables are configured
 */
export function isAIConfigured(): boolean {
  return !!(LITELLM_BASE_URL && LITELLM_API_KEY);
}

/**
 * Generates a description for an image using AI vision capabilities
 * 
 * @param imageUrl - URL of the image to analyze (can be local path or remote URL)
 * @returns AI-generated description
 * @throws AIError if the request fails
 */
export async function generateImageDescription(
  imageUrl: string
): Promise<AIDescriptionResult> {
  if (!isAIConfigured()) {
    throw new AIError(
      "AI is not configured. Please set LITELLM_BASE_URL and LITELLM_API_KEY environment variables.",
      "AI_NOT_CONFIGURED"
    );
  }

  const prompt = `You are helping describe design assets for a creative collaboration platform called Mainstream.

Analyze this image and provide a concise, engaging description (2-3 sentences) that describes:
- What the design/image shows
- Key visual elements, colors, and style
- The mood or purpose (if apparent)

Keep the tone professional but friendly. Focus on what would help other designers understand and discover this asset.

Respond with ONLY the description text, no JSON formatting or additional commentary.`;

  try {
    const response = await fetch(`${LITELLM_BASE_URL}/v1/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${LITELLM_API_KEY}`,
      },
      body: JSON.stringify({
        model: LITELLM_MODEL,
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: imageUrl } },
            ],
          },
        ],
        max_tokens: DEFAULT_MAX_TOKENS,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new AIError(
        `LiteLLM request failed: ${errorText}`,
        "LITELLM_REQUEST_FAILED",
        response.status
      );
    }

    const data = await response.json();

    // Extract the description from the response
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new AIError(
        "No description generated by AI",
        "NO_CONTENT_GENERATED"
      );
    }

    // Clean up the response (remove any potential JSON formatting or extra whitespace)
    const description = content.trim();

    return { description };
  } catch (error) {
    if (error instanceof AIError) {
      throw error;
    }

    throw new AIError(
      error instanceof Error ? error.message : "Unknown AI error",
      "AI_UNKNOWN_ERROR"
    );
  }
}

